default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: lms_dev
test:
  <<: *default
  database: lms_test
production:
  <<: *default
  database: lms_pro
